### ISSUE TITLE
Question re overflow

### ISSUE THREAD

**Issue by omniviewsports** [juniorklawa/react-native-auto-size-text#19]
Regarding the modes, is there a way to use a portion of the text followed by "...". For example, in a sports app that lists players on a football team. One example is BenJarvus Green-Ellis. Is there a way to use this tool so that if the name does not fit it would do something like this: "BenJarvus..."?

**Comment by juniorklawa** [comment]
You can use `ResizeTextMode.min_font_size` passing `ellipsizeMode="tail"`

Like this:

          <AutoSizeText
            numberOfLines={2}
            minFontSize={24}
            fontSize={40}
            ellipsizeMode="tail"
            mode={ResizeTextMode.min_font_size}>
            {text}
          </AutoSizeText>

Output:
![image](https://user-images.githubusercontent.com/7197169/159466794-59c26659-fb54-4229-87f0-c6323dc7c741.png)
